### ISSUE TITLE
Image upload fails in `request`

### ISSUE THREAD

**Issue by timvdalen** [algesten/hangupsjs#35]
Since a few days, any image upload has resulted in:

```
[project]\node_modules\q\q.js:155
                throw e;
                      ^
Error: options.uri is a required argument
    at Request.init ([project]\node_modules\hangupsjs\node_modules\request\request.js:244:31)
    at new Request ([project]\node_modules\hangupsjs\node_modules\request\request.js:140:8)
    at request ([project]\node_modules\hangupsjs\node_modules\request\index.js:55:10)
    at [project]\node_modules\hangupsjs\lib\util.js:56:22
    at Function.promise ([project]\node_modules\q\q.js:682:9)
    at req ([project]\node_modules\hangupsjs\lib\util.js:55:14)
    at ChatReq.module.exports.ChatReq.baseReq ([project]\node_modules\hangupsjs\lib\chatreq.js:49:14)
    at [project]\node_modules\hangupsjs\lib\client.js:462:28
    at _fulfilled ([project]\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done ([project]\node_modules\q\q.js:863:30)
```

**Comment by lorenzos** [comment]
Try to update. It should be fixed in #34

**Comment by timvdalen** [comment]
There's no new package version out yet, but changing that line in the compiled version on my system fixed it, thanks.

**Comment by jimeh** [comment]
Any chance we can get a new package version published to NPM with this fix? :)

**Comment by algesten** [comment]
sorted. sorry. i was slow. 1.2.0 is released.
